name: GitHub Actions Demo
run-name: "@${{ github.actor }} is testing out GitHub Actions 🚀 (${{ github.action }})"
on:
  push:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          #env
          #cat /etc/os-release
          VERSIONID=$(cat /etc/os-release | grep VERSION_ID | cut -d'=' -f2)
          echo
          echo "Version: $VERSIONID"
          echo "VERSIONID=$VERSIONID" >> "$GITHUB_ENV"
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "Which version is it? ${VERSIONID}"
      - name: Setup Git
        run: |
          export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$(pwd)/my}
          mkdir -p ${XDG_CONFIG_HOME}/git
          git config --file ${XDG_CONFIG_HOME}/git/config user.name "github-actions[bot]"
          git config --file ${XDG_CONFIG_HOME}/git/config user.email "github-actions[bot]@users.noreply.github.com"
          git config --file ${XDG_CONFIG_HOME}/git/config githubconf.env.env1 "XDG_CONFIG_HOME=${XDG_CONFIG_HOME}"
          BASE_BRANCH1=develop
          git config --file ${XDG_CONFIG_HOME}/git/config githubconf.env.env2 "BASE_BRANCH=${BASE_BRANCH1}"
          echo
          echo "List of Git config values and it's origins:"
          git config --list --show-origin
          echo
          export $(git config --file tmp/git/config githubconf.env.env2)
          echo BASE_BRANCH = ${BASE_BRANCH}
