name: PCurl-Get Release
run-name: ${{ github.event_name }} by @${{ github.actor }}

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"

# Cancel any currently running workflow(s) if the new one is started
concurrency:
  # group: ${{ github.workflow }}-${{ github.ref }}
  # Only one workflows for `master` branch
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  check-release:
    name: Check if commits to be released are pushed or cancel workflow
    runs-on: ubuntu-latest
    outputs:
      cancel_workflow: ${{ steps.last-commit-tag.outputs.cancel_workflow == 'true' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Where to store persistent Git configuration
        run: |
          touch .github/config
          cat <<EOF | tee -a .git/config >/dev/null
          # Persistent Git configuration added to .git/config
          [include]
              path = ${{ github.workspace }}/.github/config
          EOF

      - name: Setup Git
        id: git-setup
        run: |
          echo -e "Git persistent state for env file is: ${{ github.workspace }}/.github/config"
          export "GITHUBCONF=${{ github.workspace }}/.github/config"
          echo "GITHUBCONF=${GITHUBCONF}" >> "$GITHUB_ENV"
          export $(git config githubconf.env.env5)
          echo "NEW_VERSION_TAG=${NEW_VERSION_TAG}" >> "$GITHUB_ENV"

      - name: Check if release already exists
        id: release-exists
        uses: insightsengineering/release-existence-action@v1.0.0
        with:
          release-tag: ${{ env.NEW_VERSION_TAG }}

      - name: Verify version tag is on master
        if: "startsWith(github.ref, 'refs/tags/v') && steps.release-exists.outputs.release-exists == 'false'"
        id: verify-tag
        run: |
          echo "is-on-master=true" >> $GITHUB_ENV
          if git merge-base --is-ancestor ${{ github.sha }} origin/master >/dev/null 2>&1; then
            echo "Version tag '${{ github.ref }}' push to the 'master' branch"
          else
            echo "Version tag '${{ github.ref }}' push to other branch then 'master'. Skip this workflow..."
            echo "is-on-master=false" >> $GITHUB_ENV
          fi

      - name: Check that last commit has annotated tag with current release version
        if: steps.release-exists.outputs.release-exists == 'false'
        id: last-commit-tag
        run: |
          # LAST_SHA=$(git rev-parse HEAD)
          echo "cancel_workflow=true" >> "$GITHUB_OUTPUT"
          TAG_ON_MASTER="${is-on-master:-true}"
          if [ "${TAG_ON_MASTER}" = "false" ]; then
            exit 0
          fi
          TAGS_PR=$(git describe --tags --exact-match HEAD^1 2>/dev/null || true)
          TAGS=$(git describe --tags --exact-match HEAD 2>/dev/null || true)
          if [ -z "${TAGS_PR}" ]; then
            # If tag pushed not on master -- cancel workflow
            if [ -n "${TAGS}" ] && [ "${TAG_ON_MASTER}" = 'true' ]; then
              for tag in $TAGS; do
                if [[ "${tag}" == "${NEW_VERSION_TAG}" ]]; then
                  echo "Found tag equal to NEW_VERSION=${NEW_VERSION_TAG} on HEAD ($(git rev-parse --short HEAD))"
                  echo "Continue to Release..."
                  echo "cancel_workflow=false" >> "$GITHUB_OUTPUT"
                  exit 0
                fi
              done
            fi
          else
            for tag in $TAGS_PR; do
              if [[ "${tag}" == "${NEW_VERSION_TAG}" ]]; then
                echo "Found tag equal to NEW_VERSION=${NEW_VERSION_TAG} on HEAD^1 ($(git rev-parse --short HEAD^1))"
                echo "Continue to Release..."
                echo "cancel_workflow=false" >> "$GITHUB_OUTPUT"
                exit 0
              fi
            done
          fi
          echo "No tags equal to NEW_VERSION=${NEW_VERSION_TAG} found on HEAD ($(git rev-parse --short HEAD)) or HEAD^1 ($(git rev-parse --short HEAD^1))"
          echo "Cancelling workflow..."

      - name: Cancel this workflow run
        # Cancel if release already exists or 
        if: steps.last-commit-tag.outputs.cancel_workflow == 'true' || steps.release-exists.outputs.release-exists == 'true' 
        uses: actions/github-script@v7
        with:
          script: |
            core.info('No release tags found. Cancelling this workflow run...')
            await github.rest.actions.cancelWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })

      - name: Wait for cancellation
        if: steps.last-commit-tag.outputs.cancel_workflow == 'true' || steps.release-exists.outputs.release-exists == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const delay = ms => new Promise(res => setTimeout(res, ms));
            while (true) {
              core.info('Waiting for workflow to cancel...');
              await delay(5000);
            }

  just-release:
    needs: check-release
    name: Release software
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Where to store persistent Git configuration
        run: |
          touch .github/config
          cat <<EOF | tee -a .git/config >/dev/null
          # Persistent Git configuration added to .git/config
          [include]
              path = ${{ github.workspace }}/.github/config
          EOF

      - name: Setup Git
        id: git-setup
        run: |
          export "GITHUBCONF=${{ github.workspace }}/.github/config"
          echo -e "Git persistent state for env file is: ${GITHUBCONF}"
          echo "GITHUBCONF=${GITHUBCONF}" >> "$GITHUB_ENV"
          export $(git config githubconf.env.env2)
          export $(git config githubconf.env.env3)
          export $(git config githubconf.env.env4)
          export $(git config githubconf.env.env5)
          export $(git config githubconf.env.env6)
          echo "BASE_BRANCH=${BASE_BRANCH}" >> "$GITHUB_ENV"
          echo "NEW_RELEASE=${NEW_RELEASE}" >> "$GITHUB_ENV"
          echo "NEW_VERSION=${NEW_VERSION}" >> "$GITHUB_ENV"
          echo "NEW_VERSION_TAG=${NEW_VERSION_TAG}" >> "$GITHUB_ENV"
          echo "RELEASE_RUN_ID=${RELEASE_RUN_ID}" >> "$GITHUB_ENV"

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup git-cliff
        run: |
          # Get git-cliff for this platform
          cargo +stable install git-cliff
          # Generate default configuration if repository doesn't have one
          if [ -f cliff.toml ]; then
            echo "git-cliff configuration $(pwd)/cliff.toml is present in this repository ('${{ github.repository }}' on '${{ github.ref_name }}' branch)"
          else
            git-cliff --init
            echo "Created git-cliff default configuration: $(pwd)/cliff.toml"
          fi

      - name: Generate release notes with git-cliff excluding github workflows
        id: release-notes
        run: |
          echo "Generating release notes..."
          RELEASE_NOTES="$(git-cliff --config github --latest --exclude-path=".github/**/*")\n\n"
          RELEASE_NOTES+="### Platforms\n\n"
          RELEASE_NOTES+="- Linux x86-64 gnu-libc\n"
          RELEASE_NOTES+="- Linux x86-64 musl (static)\n"
          RELEASE_NOTES+="- Linux i686 gnu-libc\n"
          RELEASE_NOTES+="- Linux i686-64 musl (static)\n"
          RELEASE_NOTES+="- Linux aarch64 gnu-libc\n"
          RELEASE_NOTES+="- Linux aarch64 musl (static)\n"
          RELEASE_NOTES+="- macOS Darwin x86-64\n"
          RELEASE_NOTES+="- macOS Darwin aarch64\n\n"
          echo "notes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$RELEASE_NOTES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download binaries built for different platforms
        uses: actions/download-artifact@v8
        with:
          pattern: pcurl-get-*
          path: tmp/assets/
          merge-multiple: true
          run-id: ${{ env.RELEASE_RUN_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Platform specific compression (Linux/Macos)
        run: |
          cd tmp/assets
          sudo apt-get update
          sudo apt-get install -y unzip zip
          for i in $(echo *); do
            if [[ "${i}" == *"-linux-"* ]]; then
              mv ${i} pcurl-get
              chmod +x pcurl-get
              tar -zcvf pcurl-get "${i}.tar.gz"
              rm -f pcurl-get
            else
              mv ${i} pcurl-get
              chmod +x pcurl-get
              zip -q ${i}.zip pcurl-get
              rm -f pcurl-get
            fi
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        if: github.ref_name == 'master'
        with:
          tag_name: ${{ env.NEW_VERSION_TAG }}
          name: Release ${{ env.NEW_VERSION_TAG }}
          body: ${{ steps.release-notes.outputs.notes }}
          files: |
            tmp/assets/pcurl-get-*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post-release:
    name: Merge release back onto development branch
    needs: just-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Where to store persistent Git configuration
        run: |
          touch .github/config
          cat <<EOF | tee -a .git/config >/dev/null
          # Persistent Git configuration added to .git/config
          [include]
              path = ${{ github.workspace }}/.github/config
          EOF

      - name: Setup Git
        id: git-setup
        run: |
          echo -e "Git persistent state for env file is: ${{ github.workspace }}/.github/config"
          echo "GITHUBCONF=${{ github.workspace }}/.github/config" >> "$GITHUB_ENV"
          export $(git config githubconf.env.env2)
          export $(git config githubconf.env.env3)
          export $(git config githubconf.env.env4)
          export $(git config githubconf.env.env5)
          echo "BASE_BRANCH=${BASE_BRANCH}" >> "$GITHUB_ENV"
          echo "NEW_RELEASE=${NEW_RELEASE}" >> "$GITHUB_ENV"
          echo "NEW_VERSION=${NEW_VERSION}" >> "$GITHUB_ENV"
          echo "NEW_VERSION_TAG=${NEW_VERSION_TAG}" >> "$GITHUB_ENV"

      - name: Merge back to base development branch
        run: |
          # git checkout master
          # git pull
          # Done with the actions/checkout@v6 above
          git checkout "${BASE_BRANCH}"
          git merge ${{ github.ref_name }}  # Brings in version tag and changelog
          # Bump version toward next release by incrementing patch level (semver)
          IFS='.' read -r MAJOR MINOR PATCH <<< "${NEW_VERSION}"
          NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))"
          sed -E -i "s/^version = \"[^\"]*\"/version = \"${NEW_VERSION}\"/" Cargo.toml
          echo ${NEW_VERSION} > VERSION
          git add VERSION Cargo.toml
          git commit -m "chore(version): bump version toward next release" -- VERSION Cargo.toml
          # Push everything to origin/${BASE_BRANCH}
          git push --all origin
          # Force delete `release` branch if possible
          # git branch -D release || true
          git branch -r -D origin/release || true

  notify:
    needs: [check-release, just-release, post-release]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: |
          if [[ "${{ needs.post-release.result }}" == "success" ]]; then
            echo "✅ Workflow succeeded"
          elif [[ "${{ needs.post-release.result }}" == "cancelled" ]]; then
            echo "☑️ Workflow silently cancelled"
          else
            declare -A WF_RESULTS
            WF_RESULTS[check-release]="${{ needs.check-release.result }}"
            WF_RESULTS[just-release]="${{ needs.just-release.result }}"
            WF_RESULTS[post-release]="${{ needs.post-release.result }}"
            echo "❌ Workflow failed: ${WF_RESULTS[post-release]}"
            for key in "${!WF_RESULTS[@]}"; do
              echo "Job '${key}', status: ${WF_RESULTS[$key]}"
            done
            exit 1
          fi
