name: PCurl-Get Release
run-name: ${{ github.action }} by @${{ github.actor }}

on:
  branch_protection_rule:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  just-release:
    name: Release software
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup git-cliff
        run: |
          # Get git-cliff for this platform
          cargo install git-cliff
          # Generate default configuration if repository doesn't have one
          [ -f cliff.toml ] || git-cliff --init

      - name: Download persistent Git configuration
        uses: actions/download-artifact@v8
        with:
          name: gitconfig
          path: tmp/git/

      - name: Setup Git
        id: git-setup
        run: |
          export $(git config --file tmp/git/config github_conf.env.env1)
          export $(git config --file tmp/git/config github_conf.env.env2)
          export $(git config --file tmp/git/config github_conf.env.env3)
          export $(git config --file tmp/git/config github_conf.env.env4)
          export $(git config --file tmp/git/config github_conf.env.env5)
          echo ${XDG_CONFIG_HOME} >> "$GITHUB_ENV"
          echo ${BASE_BRANCH} >> "$GITHUB_ENV"
          echo ${NEW_RELEASE} >> "$GITHUB_ENV"
          echo ${NEW_VERSION} >> "$GITHUB_ENV"
          echo ${NEW_VERSION_TAG} >> "$GITHUB_ENV"

      - name: Generate release notes with git-cliff
        id: release_notes
        run: |
          echo "Generating release notes..."
          RELEASE_NOTES="$(git-cliff --config github --latest)\n\n"
          RELEASE_NOTES+"### Platforms\n\n"
          RELEASE_NOTES+"- macOS Darwin aarch64\n"
          RELEASE_NOTES+"- Linux x86-64\n"
          RELEASE_NOTES+"- Linux aarch64\n\n"
          echo "notes<<EOF"
          echo "$RELEASE_NOTES"
          echo "EOF"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download binaries built for different platforms
        uses: actions/download-artifact@v8
        with:
          pattern: pcurl-get-*
          path: tmp/assets/
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        if: github.ref_name == 'master'
        with:
          tag_name: ${{ env.NEW_VERSION_TAG }}
          name: Release ${{ env.NEW_VERSION_TAG }}
          body: ${{ steps.release_notes.outputs.notes }}
          files: |
            tmp/assets/pcurl-get-*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post-release:
    name: Merge release back onto development branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download persistent Git configuration
        uses: actions/download-artifact@v8
        with:
          name: gitconfig
          path: tmp/git/

      - name: Setup Git
        id: git-setup
        run: |
          export $(git config --file tmp/git/config github_conf.env.env1)
          export $(git config --file tmp/git/config github_conf.env.env2)
          export $(git config --file tmp/git/config github_conf.env.env3)
          export $(git config --file tmp/git/config github_conf.env.env4)
          export $(git config --file tmp/git/config github_conf.env.env5)
          echo ${XDG_CONFIG_HOME} >> "$GITHUB_ENV"
          echo ${BASE_BRANCH} >> "$GITHUB_ENV"
          echo ${NEW_RELEASE} >> "$GITHUB_ENV"
          echo ${NEW_VERSION} >> "$GITHUB_ENV"
          echo ${NEW_VERSION_TAG} >> "$GITHUB_ENV"

      - name: Bump version for next release
        run: |
          NEW_VERSION=${NEW_VERSION}+
          sed -E -i "s/^version = \"[^\"]*\"/version = \"${NEW_VERSION}\"/" Cargo.toml
          echo ${NEW_VERSION} > VERSION

      - name: Merge back to development branch
        run: |
          # git checkout master
          # git pull
          # Done with the action actions/checkout@v6 above
          git checkout "${BASE_BRANCH}"
          git merge ${{ github.ref_name }}  # Brings in version tag and changelog
          # Force delete `release` branch if possible and push all back into repository
          git branch -D release 2>/dev/null || true
          git push --all origin

  notify:
    needs: post-release
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: |
          echo "Release job completed with status: ${{ job.status }}"
